// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/executeScript": {
            "get": {
                "description": "executes plex2letterbox python script with current settings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data"
                ],
                "summary": "executes script",
                "responses": {
                    "200": {
                        "description": "Sucessfully executed export",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Settings may missing or are incomplete",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Unknown error during execution",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/exports": {
            "get": {
                "description": "Returns all existing exports under /data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data"
                ],
                "summary": "Returns all existing exports",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved exports",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Export"
                            }
                        }
                    },
                    "500": {
                        "description": "Unknown error during execution",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/exports/remove/{id}": {
            "delete": {
                "description": "Deletes the CSV export file with the given ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data"
                ],
                "summary": "Deletes a specific export",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Export ID (Filename)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Export successfully deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/exports/{id}": {
            "get": {
                "description": "reads CSV",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Data"
                ],
                "summary": "returns CSV of export",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Export ID (Filename)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "CSV File",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/settings": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Settings"
                ],
                "summary": "returns current setings",
                "responses": {
                    "200": {
                        "description": "Successfully returned settings",
                        "schema": {
                            "$ref": "#/definitions/models.Settings"
                        }
                    },
                    "400": {
                        "description": "Settings may missing or are incomplete",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Unknown error during execution",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/settings/save": {
            "post": {
                "description": "Receives baseurl and token and stores them in config.ini",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Settings"
                ],
                "summary": "saves settings",
                "parameters": [
                    {
                        "description": "Settings payload",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Settings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully saved settings",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Settings may be missing or are incomplete",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Unknown error during execution",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Export": {
            "type": "object",
            "properties": {
                "Date": {
                    "type": "string"
                },
                "ExportItemCount": {
                    "type": "integer"
                },
                "Name": {
                    "type": "string"
                }
            }
        },
        "models.Settings": {
            "type": "object",
            "properties": {
                "baseurl": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "BFF API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
